### PR TITLE
RN-678: Fix LESMIS dashboard date picker

### PR DESCRIPTION
**Pull request by chris-pollard**
### Changes:

- Update DashboardReport component to account for different date param inputs.

### CODE REVIEW

**Review by billli0 — CHANGES_REQUESTED** [review]
@chris-pollard This logic looks solid! Thanks for fixing it. 

Seems the date logic have been updated, could you also apply that to `DashboardReportModal` (expand page when you click 'see more'), and `DashboardReportPage` (page for PDF exporting)? 

These two components also have usage of `startDate` and `endDate`. The new logic can be reused and applied to them.

**Comment by chris-pollard** [comment]
> 

Hey @billli0 actually had a look through the components, and as the modal and export both use search params and the history api, it works perfectly. So no need for that conditional logic in the modal or export.

**Comment by billli0** [comment]
Good point @chris-pollard, seems like we don't need to do that for `DashboardReportPage`. However on `DashboardReportModal`:
https://github.com/beyondessential/tupaia/blob/c64af87a907df19cb875bfbf0d0ea5da9b8508b8/packages/lesmis/src/components/DashboardReportModal.js#L134

It fetches `startDate` and `endDate` from search params, but the `year` has been neglected, which causes that if 2018 is selected, then click `see more`, the date picker is not well addressed and it will show default period.

**Comment by chris-pollard** [comment]
> 

Good point, @billli0 I'll look at that.

**Review by billli0 — APPROVED** [review]

**Pull request merged**
