### PR TITLE
Fix mobile chart legend display

### PR DESCRIPTION
**Pull request by tcaiger**
### Changes:

- Move handling of mobile legend labels to legend component so that the legend value doesn't display on tooltips on mobile

---

### CODE REVIEW

**Review by chris-bes — APPROVED** [review]
LGTM!

**Comment by edmofro** [comment]
@tcaiger could you please point this at @IgorNadj's hot release branch so it goes out tomorrow?

**Comment by IgorNadj** [comment]
`release-2021-26-1`

**Comment by tcaiger** [comment]
Thanks Igor, I've updated the PR.

**Pull request merged**
