### PR TITLE
Add 3 new entity types

### PR DESCRIPTION
**Pull request by Alastair-L**
### Issue #:
https://github.com/beyondessential/tupaia-backlog/issues/1227
### Changes:
Added 3 new entity types.

Is this a schema migration?

### CODE REVIEW

**Review by edmofro — COMMENTED** [review]
It is a schema migration, and you've written it correctly, but I'd like to talk to Gerry about the naming before approving this

**Review by edmofro — APPROVED** [review]

**Comment by Alastair-L** [comment]
@edmofro does this need testing or can it be merged?

**Comment by edmofro** [comment]
No testing required, but always best to avoid merging something that won't be tested on the afternoon before release - hold it for tomorrow plz

**Comment by edmofro** [comment]
(my understanding is it's not needed for a while?)

**Comment by kujo4pm** [comment]
Actually chatting with @gerrybes I think this would be preferably in today's release? What do you think?

**Comment by edmofro** [comment]
Yeah sure - there's next to no risk here, so go for it

**Comment by kujo4pm** [comment]
Thanks all!

**Comment by gerrybes** [comment]
Yes. Thanks everyone. Appreciate it!

**Pull request merged**
