### PR TITLE
Change rowCount from fixed to dynamic

### PR DESCRIPTION
**Pull request by billli0**
### Issue #:
[1756: Hotfix missing Date column](https://github.com/beyondessential/tupaia-backlog/issues/1756)

### Changes:
Change rowCount from fixed to dynamic

### CODE REVIEW

**Review by edmofro — APPROVED** [review]
Approved, but also have a couple of suggestions just from reading through the same file in your original PR [here](https://github.com/beyondessential/tupaia/commit/527bcd31f981b0caf8bf16ef90fa352bc7b0ec05#r44931929), [here](https://github.com/beyondessential/tupaia/commit/527bcd31f981b0caf8bf16ef90fa352bc7b0ec05#r44931955), and [here](https://github.com/beyondessential/tupaia/commit/527bcd31f981b0caf8bf16ef90fa352bc7b0ec05#r44933038) - not sure if you want to do those changes here or in a new PR

**Comment by edmofro** [comment]
As this is a hot-fix, probably best as a new PR for those other suggestions!

**Comment by billli0** [comment]
Thanks Edwin. I will make a new PR to implement your suggestions.

**Comment by edmofro** [comment]
@billli0 can you please recreate the PR?

@BinduMadhaviTammireddy as this is a hot fix, it shouldn't be updated from dev. Rule of thumb: update from the "base branch", i.e. whatever branch is on the left when you look at the PR
Screen Shot 2020-12-09 at 11 19 53 AM

**Comment by billli0** [comment]
I'll recreate the PR.

**Comment by BinduMadhaviTammireddy** [comment]
> @billli0 can you please recreate the PR?
> 
> @BinduMadhaviTammireddy as this is a hot fix, it shouldn't be updated from dev. Rule of thumb: update from the "base branch", i.e. whatever branch is on the left when you look at the PR
> Screen Shot 2020-12-09 at 11 19 53 AM

sorry wasn't aware of it.

**Pull request closed without merging**
