### PR TITLE
1144 update tupaia logos

### PR DESCRIPTION
**Pull request by tcaiger**
### Changes:

- Update Tupaia logos to be SVG
- Add favicon icon
- Remove usued default zoomControl from map

---

### Screenshots:

**Navbar**

Screen Shot 2020-09-23 at 2 44 11 PM

**Home screen**

Screen Shot 2020-09-23 at 2 46 37 PM

**Project landing page**

Screen Shot 2020-09-23 at 2 44 03 PM

**Favicon**

Screen Shot 2020-09-04 at 10 40 27 AM

**Zoom control before**

Screen Shot 2020-09-04 at 10 45 49 AM

### CODE REVIEW

**Comment by edmofro** [comment]
Code looks good!

The font is slightly different in the svg versions of the logo (taller, the hole in the p isn't a full circle) - are we able to align it a bit more?

Also...I can't actually tell what's changed in the zoom control screenshots?

**Comment by tcaiger** [comment]
> Code looks good!
> 
> The font is slightly different in the svg versions of the logo (taller, the hole in the p isn't a full circle) - are we able to align it a bit more?
> 
> Also...I can't actually tell what's changed in the zoom control screenshots?

In regards to the logos, Dave created them. I will see if I can get him to tweak them next week.
In regards to the zoom control, the default one was not removed when the custom one was added to the bottom of the page. If you look closely below the logo you can see if poking out. It has been erking me for weeks.

**Comment by edmofro** [comment]
Oh the bit poking out in the after shot right? Yes awesome to get rid of that (I've never noticed!!)

Let's taihoa on the logo until after Dave's responded about updating the font

**Comment by tcaiger** [comment]
> Oh the bit poking out in the after shot right? Yes awesome to get rid of that (I've never noticed!!)
> 
> Let's taihoa on the logo until after Dave's responded about updating the font

Just realised the I had my before and after screenshots around the wrong way (which I have now fixed). Sorry for the confusion!

**Comment by David-G-UX** [comment]
> Code looks good!
> 
> The font is slightly different in the svg versions of the logo (taller, the hole in the p isn't a full circle) - are we able to align it a bit more?
> 
> Also...I can't actually tell what's changed in the zoom control screenshots?

@edmofro, unfortunately I don't have the original font. This was the closest font I could find. Do you have the original logo files from the Designer? I might be able to create an SVG from that

**Comment by edmofro** [comment]
Have sent you the .ai file on Slack

**Comment by tcaiger** [comment]
@edmofro I have updated the logos and added new screenshots. This is now ready for review.

**Comment by edmofro** [comment]
There's actually still one change... 😅 

The cross has turned blue. Could be an intentional thing though @David-G-UX?

**Comment by David-G-UX** [comment]
**Design:**
Error: https://www.figma.com/file/mvbowEsmvbmGuG0IvjfiW0/PSS-Admin-Desktop-Design-System?node-id=1030%3A0
Authorisation: https://www.figma.com/file/mvbowEsmvbmGuG0IvjfiW0/PSS-Admin-Desktop-Design-System?node-id=1030%3A124

Screen Shot 2020-09-16 at 11 13 50 am

**Comment by David-G-UX** [comment]
> There's actually still one change... 😅
> 
> The cross has turned blue. Could be an intentional thing though @David-G-UX?

Hi Edwin, I've double checked the Illustrator file you supplied me and the cross is actually blue on white text version of the logo. I am happy to change it to a black cross.. Let me know:)

**Comment by tcaiger** [comment]
> > There's actually still one change... 😅
> > The cross has turned blue. Could be an intentional thing though @David-G-UX?
> 
> Hi Edwin, I've double checked the Illustrator file you supplied me and the cross is actually blue on white text version of the logo. I am happy to change it to a black cross.. Let me know:)

@edmofro - my guess is that we should get Dave to quickly update the logo cross to black, right?

**Comment by edmofro** [comment]
Thanks for the reminder on this @tcaiger - yep I think so! Cheers guys

**Comment by tcaiger** [comment]
> Thanks for the reminder on this @tcaiger - yep I think so! Cheers guys

@David-G-UX - would you please be able to have a look at this today? thanks

**Comment by David-G-UX** [comment]
@tcaiger - SCG logos attached w/ black cross:)
[Tupaia_Logo_SVG.zip](https://github.com/beyondessential/tupaia/files/5264561/Tupaia_Logo_SVG.zip)

**Comment by tcaiger** [comment]
@edmofro - I have updated the logos and the screenshots. If you are happy to approve the changes, then I will mark this as ready for test.

**Review by edmofro — APPROVED** [review]
Wahoo!

**Pull request merged**
