### PR TITLE
Add Supply Chain Fiji Project

### PR DESCRIPTION
**Pull request by nick-beyondessential**
### Changes:
- new project migration

### CODE REVIEW

**Review by PShoe — APPROVED** [review]

**Comment by billli0** [comment]
Do we need to do this here: 

>   await insertObject(db, 'dashboardGroup', {
    organisationLevel: 'Project',
    userGroup: USER_GROUP,
    organisationUnitCode: PROJECT_CODE,
    dashboardReports: '{project_details}',
    name: DASHBOARDGROUP_NAME,
    code: DASHBOARDGROUP_CODE,
    projectCodes: `{${PROJECT_CODE}}`,
  });

**Comment by nick-beyondessential** [comment]
Good catch @billli0 I thought i had removed it.

**Comment by nick-beyondessential** [comment]
Oh you are asking if we need to add it? I don't think so - being only one country makes sense to jump to that country.

**Comment by billli0** [comment]
Thanks @nick-beyondessential , looks good to me!

**Pull request merged**
