### PR TITLE
Release v2021-22.0 (Due 04/06/2021)

### PR DESCRIPTION
**Pull request by billli0**
## Manual Release Steps
- [ ] Delete `REACT_APP_LESMIS_API_URL` env variable from the `lesmis` package
- [ ] Copy nginx servers config across and restart nginx

## Features ⭐ 
- [1500](https://github.com/beyondessential/tupaia-backlog/issues/1500) PSSS app endpoint: GET Country metadata
- [1337](https://github.com/beyondessential/tupaia-backlog/issues/1337) PSSS indicator: Calculate country level case number
- [1501](https://github.com/beyondessential/tupaia-backlog/issues/1501) PSSS app endpoint: GET Site metadata
- [1336](https://github.com/beyondessential/tupaia-backlog/issues/1336) PSSS indicator: Calculate the number of sentinel sites submitting in a given week
- [1411](https://github.com/beyondessential/tupaia-backlog/issues/1411) PSSS report: Unconfirmed Weekly Report per Sentinel Site
- [1369](https://github.com/beyondessential/tupaia-backlog/issues/1369) PSSS app endpoint: GET Unconfirmed Weekly Report per Sentinel Site for a Country and a Week
- [1498](https://github.com/beyondessential/tupaia-backlog/issues/1498) PSSS app endpoint: PUT/POST/DELETE Unconfirmed Weekly Report for a site
- [1506](https://github.com/beyondessential/tupaia-backlog/issues/1506) PSSS report: Active Alerts
- [1509](https://github.com/beyondessential/tupaia-backlog/issues/1509) PSSS report: Archived Alerts
- [1507](https://github.com/beyondessential/tupaia-backlog/issues/1507) PSSS report: Report per Syndrome - Confirmed Data
- [1510](https://github.com/beyondessential/tupaia-backlog/issues/1510) PSSS app endpoint: GET Active Alerts
- [1514](https://github.com/beyondessential/tupaia-backlog/issues/1514) PSSS app endpoint: GET Archived Alerts
- [1517](https://github.com/beyondessential/tupaia-backlog/issues/1517) PSSS report: Report per Syndrome - Confirmed Data per Week
- [1518](https://github.com/beyondessential/tupaia-backlog/issues/1518) PSSS report: Report per Syndrome - Confirmed Data per Week per Site
- [2775](https://github.com/beyondessential/tupaia-backlog/issues/2775) PSSS: Create alerts on confirm
- [1600](https://github.com/beyondessential/tupaia-backlog/issues/1600) PSSS: Show a message when an alert has been created
- [2806](https://github.com/beyondessential/tupaia-backlog/issues/2806) PSSS app endpoints: GET data for syndromes
- [1511](https://github.com/beyondessential/tupaia-backlog/issues/1511) PSSS app endpoint: GET Active Alerts per Country
- [1515](https://github.com/beyondessential/tupaia-backlog/issues/1515) PSSS app endpoint: GET Archived Alerts per Country
- [2827](https://github.com/beyondessential/tupaia-backlog/issues/2827) PSSS: Mark alert as archived
- [2836](https://github.com/beyondessential/tupaia-backlog/issues/2836) PSSS: Restore archived alert
- [2838](https://github.com/beyondessential/tupaia-backlog/issues/2838) PSSS: Delete archived alert
- [2803](https://github.com/beyondessential/tupaia-backlog/issues/2803) PSSS: Make alert columns sortable
- [2244](https://github.com/beyondessential/tupaia-backlog/issues/2244) Support entity aggregation in the database

## Tweaks ⚖️
- [2853](https://github.com/beyondessential/tupaia-backlog/issues/2853) Change to the threshold for DLI, ILI, DIA and PF in PSSS

## Visualisations 📊 
- [2364](https://github.com/beyondessential/tupaia-backlog/issues/2364) Laos EOC Dashboard: Measles commodity table
- [2365](https://github.com/beyondessential/tupaia-backlog/issues/2365) Laos EOC Dashboard: Dengue Commodities Traffic Light table
- [2366](https://github.com/beyondessential/tupaia-backlog/issues/2366) Laos EOC  Dashboard Measles Critical Items Availability
- [2379](https://github.com/beyondessential/tupaia-backlog/issues/2379) Laos EOC Overlay: Measles Vaccine Stock Availability by Facility
- [2643](https://github.com/beyondessential/tupaia-backlog/issues/2343) Laos EOC Dashboard: Dengue bar chart District
- [2644](https://github.com/beyondessential/tupaia-backlog/issues/2644) Laos EOC Map Overlay: Weekly Dengue Cases by District
- [2645](https://github.com/beyondessential/tupaia-backlog/issues/2645) Laos EOC Map Overlay: Weekly Malaria Cases by Province 
- [2647](https://github.com/beyondessential/tupaia-backlog/issues/2647) Laos EOC Dashboard: Malaria cases bar chart at district and province 
- [1642](https://github.com/beyondessential/tupaia-backlog/issues/1642) PSSS vis num sentinel sites (#2367) 
- [1641](https://github.com/beyondessential/tupaia-backlog/issues/1641) PSSS vis Country Level Dashboard: 2 Y axis (#2376) 
- [1638](https://github.com/beyondessential/tupaia-backlog/issues/1638) PSSS vis Country Level Dashboard: Trend Graph (#2384) 
- [2107](https://github.com/beyondessential/tupaia-backlog/issues/2107) PSSS vis Syndromic Surveillance Case Numbers Heat map (#2444) 
- [2108](https://github.com/beyondessential/tupaia-backlog/issues/2108) PSSS vis Map Overlay Radius (Bubble) Map (#2444 same PR above) 
- [2104](https://github.com/beyondessential/tupaia-backlog/issues/2104) PSSS vis Facility Level Daily Cases Trend Graph (#2414) 
- [2105](https://github.com/beyondessential/tupaia-backlog/issues/2105) PSSS vis National Level Dashboard, Daily Cases Trend Graph (#2414 same PR above) 
- [1750](https://github.com/beyondessential/tupaia-backlog/issues/1750) PSSS vis Country Level Dashboard,Past years data overlaid  (#2503) 
- [2109](https://github.com/beyondessential/tupaia-backlog/issues/2109) PSSS vis Country Level Dashboard: Weekly Cases Trend Graph  (#2471) 
- [2111](https://github.com/beyondessential/tupaia-backlog/issues/2111) PSSS vis Palau Facility Level Weekly Case Number Trend Graph  (#2471 same PR above) 
- 
## Bug fixes 🐛 
- [2890](https://github.com/beyondessential/tupaia-backlog/issues/2890) Laos school Raw Data Download does not return values for some fields
- [2663](https://github.com/beyondessential/tupaia-backlog/issues/2663) Submitting a response in PSSS does not show that response to the user until after a few seconds
- [2874](https://github.com/beyondessential/tupaia-backlog/issues/2874) Sentinel case table doesn't get clear if you go to next site without pressing save button
- [2833](https://github.com/beyondessential/tupaia-backlog/issues/2833) Can't log in on lesmis.la

## Infrastructure and maintenance 🛠️
- [No issue](https://github.com/beyondessential/tupaia/pull/2593) Add aggregations and `transform->aggregate->avg` aggregation in report server
- [No issue](https://github.com/beyondessential/tupaia/pull/2620) Add utility script for running analytics full refresh
- [No issue](https://github.com/beyondessential/tupaia/pull/2623) Update index in utility script to match psss phase 2 branch
- [No issue](https://github.com/beyondessential/tupaia/pull/2457) Add 'psss' hierarchy to report request
- [2714](https://github.com/beyondessential/tupaia-backlog/issues/2714) Improve performance of 'PSSS_Total_Sites_Reported' indicator
- [No issue](https://github.com/beyondessential/tupaia/pull/2615/commits/7248d9e6b4fda6aa4247ae1d6ea7a5958ed8e31f) Allow fetching event data values
- [2842](https://github.com/beyondessential/tupaia-backlog/issues/2842) Public Data now available when access micro-services

### CODE REVIEW

**Comment by kael89** [comment]
@EMcQ-BES a few notes to ease your card-matching burden:

* The following cards are mentioned in the commit history but are already closed: **1709**, **2677**. The reason is that their code is already copied & merged in `dev` and `production `
* The commits that mention **1506** also implement **1509** (see the [PR](https://github.com/beyondessential/tupaia/pull/2541))
* The commit with message "1510: Alert data per syndrome report" mentions a wrong card number - the actual card is **1507** (see the [PR](https://app.zenhub.com/workspace/o/beyondessential/tupaia/issues/2550)). **1510** is still included in the notes since it is implemented in another commit ("1510-1514: PSSS - Show alerts")
* I haven't mentioned merge/ad hoc fixes related to cards already in the list. The reason was to keep the release notes a bit more meaningful. Hopefully it's easy to tell apart which commits fall in this category (eg "PSSS: Minor UI fixes")
* **1117** is mentioned in the commits but not in the release notes, because it was subsequently reverted in https://github.com/beyondessential/tupaia/pull/2604. Sorry for that - I should have probably made it more obvious with a revert commit!

**Comment by nick-beyondessential** [comment]
**Laos EOC Visuals Pt3 epic branch:**

**Comment by billli0** [comment]
**PSSS Visuals epic branch:**

1642 psss vis num sentinel sites (#2367)
1641 Country Level Dashboard: 2 Y axis (#2376)
1638 Country Level Dashboard: Trend Graph (#2384)
2107 Syndromic Surveillance Case Numbers Heat map (#2444)
2108 Map Overlay Radius (Bubble) Map (#2444 same PR above)
2104 Facility Level Daily Cases Trend Graph (#2414)
2105 National Level Dashboard, Daily Cases Trend Graph (#2414 same PR above)
1750 Country Level Dashboard,Past years data overlaid (#2503)
2109 Country Level Dashboard: Weekly Cases Trend Graph (#2471)
2111 PSSS Palau Facility Level Weekly Case Number Trend Graph (#2471 same PR above)

merged in from epic branch PR: https://github.com/beyondessential/tupaia/pull/2381

**Comment by EMcQ-BES** [comment]
Copied to #2629, closing this PR

**Pull request closed without merging**
