### PR TITLE
no-issue: Change the name that appears in the email inbox to Tupaia

### PR DESCRIPTION
**Pull request by rohan-bes**
image
Top: new
Bottom: old

### CODE REVIEW

**Comment by jaskfla** [comment]
Which name are you referring to here?

On my end, I can see that it now says "Hi Jasper” instead of “Hi admin-panel-server@…” or “Hi tupaia-server@…”, but the sender name still appears as _admin_ rather than _Tupaia_ 🤔

**Comment by rohan-bes** [comment]
> Which name are you referring to here?
> 
> On my end, I can see that it now says "Hi Jasper” instead of “Hi admin-panel-server@…” or “Hi tupaia-server@…”, but the sender name still appears as _admin_ rather than _Tupaia_ 🤔

@jaskfla It should look like this with the sender being `Tupaia <admin@tupaia.org>`
image

**Review by jaskfla — APPROVED** [review]
I can’t seem to replicate the new behaviour on my end, but am inclined to trust that this is an error on my part; given it aligns with the Nodemailer documentation and clearly works on your system

**Comment by rohan-bes** [comment]
> I can’t seem to replicate the new behaviour on my end, but am inclined to trust that this is an error on my part; given it aligns with the Nodemailer documentation and clearly works on your system

Just to be sure, you've rebuilt `@tupaia/server-utils` package?

**Comment by jaskfla** [comment]
> Just to be sure, you've rebuilt `@tupaia/server-utils` package?

I have, yes 😕

Screenshot 2024-01-30T134643

**Comment by rohan-bes** [comment]
Okay, that's odd... I'll test this one on a feature branch to be sure what the behaviour looks like then

**Comment by jaskfla** [comment]
@rohan-bes Working!

Looks like I needed to rebuild and explicitly restart my server. Probably just my system failing or being slow to hot-reload. Sorry about the confusion!@

**Pull request merged**
