### PR TITLE
841: Laos Schools School Level Dashboard: Student Numbers Table

### PR DESCRIPTION
**Pull request by chris-bes**
### Changes:
-  Added laos schools number of students matrix school level

### Screenshots:
- https://github.com/beyondessential/tupaia-backlog/issues/841#issuecomment-695912619

### CODE REVIEW

**Review by Alastair-L — COMMENTED** [review]
Nice work! Same thing with this one and https://github.com/beyondessential/tupaia-backlog/issues/902 though in that the card specifies a table. And work that you do for that card could maybe be duplicated here? What do you think?

**Comment by chris-bes** [comment]
> Nice work! Same thing with this one and beyondessential/tupaia-backlog#902 though in that the card specifies a table. Work that you do for that card could maybe be used here? What do you think?

Sorry @Alastair-L , I don't quite get what you mean... which work do you have in mind from #902 that can be reused here?

**Comment by Alastair-L** [comment]
Just a similar comment to https://github.com/beyondessential/tupaia/pull/1322#discussion_r488309278. The mockup for this card looks like this: 
image

And the type is "Table". 

If you make changes to https://github.com/beyondessential/tupaia-backlog/issues/902 to make the matricies look more like tables (such as mentioned here: https://github.com/beyondessential/tupaia-backlog/issues/902#issuecomment-693197661) then perhaps those same changes would be useful in this card. 

However, happy to approve if you disagree.

**Comment by chris-bes** [comment]
@Alastair-L ahh got it, thanks for your thought! What I was going to do more in https://github.com/beyondessential/tupaia-backlog/issues/902#issuecomment-693197661 is just to remove unused space so I think that's not going to apply here?

**Comment by Alastair-L** [comment]
Sure! Sounds good! (I wasn't sure exactly what you were investigating)

**Review by Alastair-L — APPROVED** [review]
LGTM!

**Comment by chris-bes** [comment]
Updated matrices to be like -> https://github.com/beyondessential/tupaia-backlog/issues/841#issuecomment-697105976

**Review by Alastair-L — APPROVED** [review]
Looks good (sorry for the delay)

**Pull request merged**
