### PR TITLE
1214 laos eoc population tileset

### PR DESCRIPTION
**Pull request by tcaiger**
### Changes:

- Add new thumbnail and map url as an option to tilesets
Note: the actual tileset does not show up on web front end unless the population key is added in admin panel

---

### CODE REVIEW

**Review by edmofro — APPROVED** [review]
lgtm :-)

**Comment by edmofro** [comment]
@kael89 a final one that I believe can be merged for tomorrow's release

**Comment by kael89** [comment]
@tcaiger successfully merged this into dev to be release tomorrow - hopefully this is fine!

**Comment by tcaiger** [comment]
Thanks - I've just added a release note.

**Pull request merged**
