### PR TITLE
258 covidau active cases indicator

### PR DESCRIPTION
**Pull request by Alastair-L**
### Issue #:
https://github.com/beyondessential/tupaia-backlog/issues/258
### Changes:
Note: I have named the indicator `COVIDAU_DELTA_ACTIVE_CASES` to better represent what it is.
Also, I question the formula for active cases, as is mentioned on the card, but that is irrelevant.
### Screenshots:
On card: https://github.com/beyondessential/tupaia-backlog/issues/258#issuecomment-688645238

### CODE REVIEW

**Review by kael89 — APPROVED** [review]

**Comment by kael89** [comment]
@Alastair-L please hold merge until https://github.com/beyondessential/tupaia-backlog/issues/258#issuecomment-688665069 is answered

**Comment by kael89** [comment]
@Alastair-L good job mate, but I will close this since the original task is no longer required (see https://github.com/beyondessential/tupaia-backlog/issues/258)

**Comment by Alastair-L** [comment]
@kael89, do you think there is any value in merging the default value stuff for the strive indicators?

**Comment by kael89** [comment]
> @kael89, do you think there is any value in merging the default value stuff for the strive indicators?

Most definitely! They are already merged in https://github.com/beyondessential/tupaia/pull/1012 😉

**Pull request closed without merging**
