### PR TITLE
1437 Covid Samoa age by flight matrix

### PR DESCRIPTION
**Pull request by IgorNadj**
### Changes:

- Add number and percentage formatter
- Allow matricies to have row and column value formatters
- Add Flight class for covid samoa
- Add valueAndPercentageByAgeByFlightDate for covid samoa
- Add Covid Samoa age by flight matrix

---

### Screenshots:
https://github.com/beyondessential/tupaia-backlog/issues/1437#issuecomment-757581610

### CODE REVIEW

**Review by nick-beyondessential — APPROVED** [review]
LGTM

**Comment by edmofro** [comment]
@kael89 I believe this can be merged for tomorrow's release, but @IgorNadj is off sick...do you want to be bold and merge it?

**Comment by kael89** [comment]
@IgorNadj successfully merged this into `dev` to be release tomorrow - hopefully this is fine!

**Comment by kael89** [comment]
@IgorNadj I also added a [release note](https://github.com/beyondessential/tupaia/pull/1871)

**Pull request merged**
