### PR TITLE
Run yarn workspaces foreach run lint:fix

### PR DESCRIPTION
**Pull request by IgorNadj**

### CODE REVIEW

**Review by edmofro — CHANGES_REQUESTED** [review]
Have done spot checking and lgtm. Suggest though we remove the web-frontend package, as that will create conflicts with the rewrite that is well underway

**Comment by IgorNadj** [comment]
>Have done spot checking and lgtm. Suggest though we remove the web-frontend package, as that will create conflicts with the rewrite that is well underway

I think it be should ok, https://beyondessential.slack.com/archives/C032DCHKTGR/p1687487133441529?thread_ts=1687392655.202379&cid=C032DCHKTGR

**Review by edmofro — APPROVED** [review]
Great, glad to see the back of this!

**Review by edmofro — COMMENTED** [review]
Noting the build failure

**Pull request merged**
