### PR TITLE
Add comment to avoid calculation when checking max length

### PR DESCRIPTION
**Pull request by Alastair-L**
### Issue #: No issue

Just adding a comment, as I have put 64 - 17 - 1 into my calculator about 5 times 😂. (Could also be useful for any new devs that join in the future)

### CODE REVIEW

**Review by kael89 — APPROVED** [review]
Looks good! (But you know what they say about comments being easy to become outdated...)

Another solution would be to `echo $MAX_BRANCH_NAME_LENGTH` in your local, for debugging purposes. Or if you think this information is always useful, perhaps update the script to print the max length even when the check succeeds. Currently it does so on failure, see line 41

**Comment by Alastair-L** [comment]
Yeah that's a good point about echoing it (I never think to run ci/cd scripts locally)!

I definitely see what you mean about the comment becoming outdated, but:
a) The comment is datestamped, which may assist in determining if it is outdated or not
b) `tonga-aggregation` is pretty long, so I see it as entirely possible that we'll have this limit for a long time
c) The comment is next to all logic which could possibly change the length, so any future changer is likely to see it and update it.

I don't think that this information is useful enough to merit always logging it unfortunately (I think forgetting the max length might be a bit of a me thing)

**Comment by Alastair-L** [comment]
Also, may I merge this without testing as it is just a comment?

**Comment by kael89** [comment]
> Yeah that's a good point about echoing it (I never think to run ci/cd scripts locally)!
> 
> I definitely see what you mean about the comment becoming outdated, but:
> a) The comment is datestamped, which may assist in determining if it is outdated or not
> b) `tonga-aggregation` is pretty long, so I see it as entirely possible that we'll have this limit for a long time
> c) The comment is next to all logic which could possibly change the length, so any future changer is likely to see it and update it.
> 
> I don't think that this information is useful enough to merit always logging it unfortunately (I think forgetting the max length might be a bit of a me thing)

I also agree with your points, they should mitigate the risk of this comment becoming outdated 🙂 Feel free to merge directly!

**Pull request merged**
