### PR TITLE
If image already on S3, log error rather than blocking sync

### PR DESCRIPTION
**Pull request by edmofro**

### CODE REVIEW

**Review by kael89 — APPROVED** [review]
That will do!

Idea (for another day): the sync process could have a specific error handling logic, which chooses which errors should block it and which not. With this in place we could still throw the error here, keeping the error handling concern out of this util.

**Comment by edmofro** [comment]
That's a good idea...

Note that the function I put it inside is not the common util that handles the s3 upload, but just the handy function used by the sync endpoint (`/changes`) handler, so it kind of operates in the way you said above, but just not as a generic pattern. A side note off that - the handler helper is probably in the wrong directory!

**Comment by edmofro** [comment]
I have tested this locally fairly thoroughly as part of an investigation into the effect of timeouts, so feel comfortable that it can be merged without independent testing (especially given it is a hot fix and a simple change). What do you think @kael89?

**Comment by kael89** [comment]
> I have tested this locally fairly thoroughly as part of an investigation into the effect of timeouts, so feel comfortable that it can be merged without independent testing (especially given it is a hot fix and a simple change). What do you think @kael89?

Sounds great @edmofro , probably this is the most pragmatic approach for testing changes like this! Go for it

**Pull request merged**
