### PR TITLE
1069 textbook student ratio bars

### PR DESCRIPTION
**Pull request by Alastair-L**
### Issue #:
https://github.com/beyondessential/tupaia-backlog/issues/1069
### Changes:
Simple migration, plus a small frontend change to support clamping (which may not be needed in the end)

### Screenshots: on card

### CODE REVIEW

**Review by nick-beyondessential — APPROVED** [review]
Looks good to me :)

**Comment by Alastair-L** [comment]
Requesting rereview for the last 9 commits 🙏

**Comment by edmofro** [comment]
@nick-beyondessential it looks like @Alastair-L has requested your re-review on this, could you please follow up?

**Comment by nick-beyondessential** [comment]
My apologies @Alastair-L! will review this now.

**Review by nick-beyondessential — APPROVED** [review]
Looks good to me

**Comment by Alastair-L** [comment]
Thanks Nick (and Edwin)

**Pull request merged**
