### PR TITLE
Add/Edit indicators in admin-panel

### PR DESCRIPTION
**Pull request by nick-beyondessential**
https://github.com/beyondessential/tupaia-backlog/issues/1255

Exposing Indicators via Admin Panel

In This PR:
- Add an Indicators tab under Visualisations in admin panel
- Includes list, add, edit

In following PR
- delete?
- in use validation

### CODE REVIEW

**Comment by edmofro** [comment]
@nick-beyondessential looking good. Unfortunately comes at a time during which we're reworking the backend to add permissions, so there's a bit more work to go here.

Could you please make these changes off the end of https://github.com/beyondessential/tupaia/pull/1382, and talk with @chris-bes or @EMcQ-BES about what's involved? Could be a good chance for some pairing ;-)

**Comment by nick-beyondessential** [comment]
Also need to check that adding indicator also adds datasource.

**Comment by edmofro** [comment]
@nick-beyondessential how did you get on with doing this against the permissions changes branch?

**Comment by nick-beyondessential** [comment]
@edmofro I have created a new PR off branch: epic-984-meditrak-server-permissions 
here: https://github.com/beyondessential/tupaia/pull/1492

**Comment by edmofro** [comment]
Closing this in favour of the new PR

**Pull request closed without merging**
