### PR TITLE
Fixup sorting answers when requesting via survey response

### PR DESCRIPTION
**Pull request by EMcQ-BES**
### Changes:

- Add joins when requesting answers via survey requests
- Sort answers by screen number and component number

### CODE REVIEW

**Review by edmofro — APPROVED** [review]
lgtm, just that unit test to work out

**Review by edmofro — APPROVED** [review]

**Comment by edmofro** [comment]
Happy for this to be merged straight away and then tested in production 

Was there ever a card created for the bug?

**Comment by EMcQ-BES** [comment]
> Was there ever a card created for the bug?

Nope, I'll make a card now describing the issue so the testers have something to work against

**Comment by edmofro** [comment]
Thanks :+1:

**Pull request merged**
