### PR TITLE
Bug Fix: Admin Panel Imports

### PR DESCRIPTION
**Pull request by tcaiger**
### Changes:

- connect ImportModal to redux store
- dispatch data change and success actions which trigger a refresh of the data fetching table after import success

### CODE REVIEW

**Review by kael89 — APPROVED** [review]
Nice fix!

**Comment by edmofro** [comment]
@kael89 I believe this can be merged for tomorrow's release, but @tcaiger is off sick...do you want to be bold and merge it?

**Comment by kael89** [comment]
@tcaiger successfully merged this into dev to be release tomorrow - hopefully this is fine!

**Comment by tcaiger** [comment]
Thanks - I've just added a release note for this as well.

**Pull request merged**
