### PR TITLE
Fix webpack config

### PR DESCRIPTION
**Pull request by kael89**
CI/CD picked that

### CODE REVIEW

**Review by edmofro — APPROVED** [review]
tbh this is a handwave

**Comment by kael89** [comment]
It's the equivalent change to https://github.com/beyondessential/tupaia/pull/1413/files => `packages/web-frontend/config/webpack.config.dev.js`, I just messed up with the change. CI/CD will be the best judge whether this actually works, I'll wait for the pipeline to finish

**Comment by kael89** [comment]
Eventually I had to use a `babel.config.js`, and everyone seems to be happy with it:

* `yarn build` => production build
* `yarn start-dev` => dev build
* `yarn test` => Jest
* `yarn cypress:generate-config` => babel-node

**Comment by kael89** [comment]
Closing in favour of https://github.com/beyondessential/tupaia/pull/1425 (invalid branch name)

**Pull request closed without merging**
