### PR TITLE
Add Laos eoc historic weather dashboard

### PR DESCRIPTION
**Pull request by IgorNadj**
### Changes:

- Add Laos eoc historic weather dashboard

---

### Screenshots:
See backlog ticket

### CODE REVIEW

**Review by rohan-bes — APPROVED** [review]
Dashboard config looks really nice here! Good job.

I took a look at the dashboard screenshot in the ticket, and while it looks really nice, it suffers from an issue of there being no clarity as to which yAxis corresponds to which line. This dashboard is by no means the only dashboard that has this issue in Tupaia, however this one to me was particularly unclear as the values of each scale are so similar (ie. It seems equally plausible that the yearly temperature fluctuated between 40 and 20 degrees with 35mm peak daily rainfall, as if the yearly temperature fluctuated between 30 and 10 degrees with 55mm peak daily rainfall).

I took a look into how easy it would be to implement labels per yAxis, however it seems that it would overlap with some existing (broken) functionality so I think it's definitely out of the scope for this PR. I've raised a ticket to address this: https://github.com/beyondessential/tupaia-backlog/issues/1262

I'm approving this PR, however I really do this that we ought to implement the multiple yAxis labelling feature (or something similar) soon and apply that to this dashboard. How do you feel @IgorNadj?

**Comment by IgorNadj** [comment]
@rohan-bes do you mean it's hard to see immediately which y axis is for rainfall and which is for temperature? If so yeah that's something I've noticed not just here but with these kinds of graphs out in the wild over the past few years... maybe a question for data people. I always struggle with these, maybe data people don't struggle so much?

**Comment by rohan-bes** [comment]
> @rohan-bes do you mean it's hard to see immediately which y axis is for rainfall and which is for temperature? If so yeah that's something I've noticed not just here but with these kinds of graphs out in the wild over the past few years... maybe a question for data people. I always struggle with these, maybe data people don't struggle so much?

Yep, that's exactly the issue. In the ticket I raised there's a link to another ticket raised by @geofish76 (https://github.com/beyondessential/tupaia-backlog/issues/1079) who experienced the same confusion with another graph in Tupaia. I think labelling the axis is probably the easiest solution, though there may be better options out there...

**Comment by IgorNadj** [comment]
Closing, will create a new PR because branch name has changed

**Comment by IgorNadj** [comment]
New PR: https://github.com/beyondessential/tupaia/pull/1476

**Pull request closed without merging**
