### PR TITLE
NO-ISSUE: Fix ObjectLikeKeys type error, add ObjectLikeFields

### PR DESCRIPTION
**Pull request by chris-pollard**
### Changes:

- Fix type error in server-boilerplate package, add ObjectLikeFields type.

### CODE REVIEW

**Review by rohan-bes — CHANGES_REQUESTED** [review]
Great stuff, thanks @chris-pollard!

Any chance I can ask you to move `Flatten` into the `tsutils` package as well, it's defined in both `entity-server` and `server-boilerplate` as well

**Comment by chris-pollard** [comment]
@rohan-bes this should do it.

**Comment by chris-pollard** [comment]
@rohan-bes  just checking if those changes were sufficient? Thanks

**Review by rohan-bes — APPROVED** [review]
Nice! Thanks @chris-pollard

**Pull request merged**
