### PR TITLE
SOL-78 SOL-79 SOL-84 SOL-85 Add overlays for two mosquito genus for country and district

### PR DESCRIPTION
**Pull request by PShoe**
### Issue #: SOL-79 

1. Map Overlay: Anopheles (district)
2. Map Overlay: Aedes (district)
3. Map Overlay: Anopheles (country)
4. Map Overlay: Aedes (country)

- [x] Needs to go after PR #3043 Sol 43&44 map overlay anopheles & aedes is merged for map overlay group 'Mosquito_occurrence_by_genus' (this included field station)

### Changes:

- Example

---

### CODE REVIEW

**Review by billli0 — APPROVED** [review]
LGTM!

**Comment by billli0** [comment]
@PShoe Would you like to change the base from `dev` to `sol-285-mosquito-overlays-district` so that we can test in one epic?

**Comment by PShoe** [comment]
> @PShoe Would you like to change the base from `dev` to `sol-285-mosquito-overlays-district` so that we can test in one epic?

@billli0 - I'm sorry I missed this until just now.  🙁  Is it fine to just send these through to dev now as they've all passed testing, or would you still like to have on the one epic branch?

**Comment by billli0** [comment]
@PShoe All good 😄 as it is test pass let's merge into dev.

**Pull request merged**
