### PR TITLE
Hotfixes

### PR DESCRIPTION
**Pull request by Alastair-L**
2 changes bundled into 1:
### Change 1: Fix expanded dialog sometimes shows the wrong report
The UPDATE_MEASURE_CONFIG action was sometimes being called after the overlay was already closed. This change stops that.

### CODE REVIEW

**Review by edmofro — APPROVED** [review]
lgtm

**Comment by Alastair-L** [comment]
Please do NOT merge this as it has had dev merged into it and is pointing at master.

**Comment by Alastair-L** [comment]
^ Have created a new branch.

**Comment by Alastair-L** [comment]
Closed in favor of: https://github.com/beyondessential/tupaia/pull/1365

**Pull request closed without merging**
