### PR TITLE
3025: Add stacked bar for complete/incomplete schools

### PR DESCRIPTION
**Pull request by EMcQ-BES**
### Changes:

- No change to utils

### Screenshots:
Attached to ticket

### CODE REVIEW

**Review by edmofro — APPROVED** [review]
One question added to the ticket https://github.com/beyondessential/tupaia-backlog/issues/3025#issuecomment-870174097

But otherwise lgtm

**Review by edmofro — CHANGES_REQUESTED** [review]
Darn she wants the hover!

**Comment by EMcQ-BES** [comment]
There are updated screenshots on the ticket for these changes

**Review by edmofro — APPROVED** [review]
Nice solve

**Pull request merged**
