### PR TITLE
Add province and national level details tables Laos

### PR DESCRIPTION
**Pull request by Alastair-L**
### Issue #:
https://github.com/beyondessential/tupaia-backlog/issues/1051
### Changes:
A simple migration

Also note the branch structure here: 
`1051-province-nation-details-tables-laos` -> `1050-district-details-table-laos` -> `839-school-details-table-laos` -> `dev`

### CODE REVIEW

**Comment by edmofro** [comment]
@Alastair-L is this one awaiting review?

**Comment by chris-bes** [comment]
@edmofro yep I'm reviewing it now 👍

**Review by chris-bes — APPROVED** [review]
Looks great!

**Comment by Alastair-L** [comment]
Forced pushed as dev was merged straight to this branch earlier

**Comment by Alastair-L** [comment]
Forced pushed as dev was merged straight to this branch earlier (again...)

**Pull request merged**
