### PR TITLE
[HOT FIX] WAI-952: Add remote tracking of correct branch, if it exists

### PR DESCRIPTION
**Pull request by edmofro**
### Issue #:
- WAI-952

### CODE REVIEW

**Review by kael89 — APPROVED** [review]
Nice fix!

**Comment by edmofro** [comment]
I've tested this through calls to it using branches that both exist and do not, so will merge straight to master

**Comment by kael89** [comment]
@edmofro should we merge this in `dev` too? (Even if it doesn't affect its functionality for now)

**Comment by edmofro** [comment]
I'm just debugging dev and feature deployment startups and would rather hold off until after that

**Comment by kael89** [comment]
> I'm just debugging dev and feature deployment startups and would rather hold off until after that

Sure thing!

**Pull request merged**
