### PR TITLE
no-issue: Switched back to mainline mathjs and bumped version

### PR DESCRIPTION
**Pull request by rohan-bes**
Not sure what changed, but everything works now

### CODE REVIEW

**Comment by IgorNadj** [comment]
Do you mind checking if meditrak app builds with this? In app center as well, that's where there was an issue.

**Comment by rohan-bes** [comment]
@IgorNadj Good call! We are green ✅ https://appcenter.ms/orgs/Beyond-Essential/apps/Tupaia-MediTrak-Android/build/branches/bump-mathjs/builds/1895

**Review by IgorNadj — APPROVED** [review]
Thanks heaps! 
Do you mind deleting the forked repo and nmp package? Or let me know and I can.

**Comment by rohan-bes** [comment]
> Do you mind deleting the forked repo and nmp package? Or let me know and I can.
@IgorNadj I might need to ask you to do that. I don't have permissions to delete that repo.

**Comment by IgorNadj** [comment]
> > Do you mind deleting the forked repo and nmp package? Or let me know and I can.
> > @IgorNadj I might need to ask you to do that. I don't have permissions to delete that repo.

All done :)

**Pull request merged**
